### PR TITLE
lowercase library naming

### PR DESCRIPTION
**Pull request by Zer0xFF**
thats how the names are set in default built

### CODE REVIEW

**Comment by Orphis** [comment]
You're supposed to link against names like "Boost::foobar", not use -lBoost_foobar.
The goal is to conform to the FindBoost module in recent CMake versions so that this could be a direct replacement.

**Comment by Zer0xFF** [comment]
[this](https://github.com/jpd002/Play-/tree/master/build_unix) linux example which relys on buildng the libraries using cmake, but the qt ui using qmake, I still need to use the libraries directly -lboost_system

Edit: im not an expert on how cmake works, but I think this change shouldnt affect that anyway, no?

**Comment by Orphis** [comment]
Proper old style CMake would be:
```
find_package(Boost REQUIRED COMPONENTS system filesystem chrono)
include_directories(${Boost_INCLUDE_DIRS})
list(APPEND PROJECT_LIBS ${Boost_LIBRARIES})
````

Modern CMake would be:
```
find_package(Boost REQUIRED COMPONENTS system filesystem chrono)
list(APPEND PROJECT_LIBS Boost::system Boost::filesystem Boost::chrono)
```

With my code, you just "add_subdirectory" my code and then use the same names "Boost::system" to link against, no more find_package (though I may provide a compatibility script to override it).

**Comment by Orphis** [comment]
The big difference being that old style CMake you pass strings around, link against it and CMake will try to match it to an actual library. `target_link_libraries(foo bar)` will convert to -lbar automatically. But that is confusing as you don't know when reading the code if you actually have a target with that name or use the automatic search. 

In modern CMake, you will have a library entity with a proper name (Library::component) you can link against. It's an imported library usually, or in my case a real library target (whose actual name shouldn't matter) and a compatibility alias.

**Comment by Zer0xFF** [comment]
but my issue isn't with cmake at all, your example works with and without my commit.

I'm referring to that fact I need to find the boost libraries for qt thats being built with qmake which reads the library location from ui_unix.pro file.

perhaps your giving me too much credit for the commit, look at this this way, I only need to change the libary name from libBoost_foobar.a to libboost_foobar.a to keep compatibility with other parts of the project, perhaps (parts of) the commit was an overkill?

**Comment by Orphis** [comment]
I think the proper fix would be to get rid of the QMake build and focus on CMake. 
CMake can build Qt applications just fine and more. The more build systems, the more complicated it is to maintain a project and deal with its cross-platform nature.

**Comment by Orphis** [comment]
Alternatively, don't try to use prebuilt binaries from this module with foreign build systems, it's not its goal at all. QMake can continue using system binaries or other sources.

**Comment by Zer0xFF** [comment]
that was my initial thinking, but kept it the way it is in favour of the qt project file, since it's easier to navigate the qt code with the qt creator, but that’s a discussion for another repo.

`Alternatively, don't try to use prebuilt binaries from this module with foreign build systems, it's not its goal at all. QMake can continue using system binaries or other sources.`

but then, in this very case, those binaries would be built twice, making this particularly useless in my example.

anyway, one last example and this is from Cmake FindBoost page itself `# e.g. "date_time" for "libboost_date_time"` the boost named in lowerclass, nor do i think cmake should make the call on library naming convention. Edit: should have linked to my [repo](https://github.com/Thunder07/Play-/blob/travis_linux_osx_android/build_unix/CMakeLists.txt) since I'm using your repo right now, you'd see I'm using boost in cmake, but I need it again for the qt side as well.

if you dont agree with me, feel free to close this PR, Thanks.

**Comment by Orphis** [comment]
Well QtCreator can use CMake files directly too. So you don't need QMake for that.

And why would you build the libraries twice? Do you partially build some libraries from CMake and some others from QMake? If you don't use another build system, the actual library name is totally irrelevant and purely symbolic. The build artifacts are not made to be shared with other build systems, you could consider them an implementation detail.

Anyway, I can always add something to change the output name of the library without changing its logical name in CMake.

As for your project, it's correctly using modern FindBoost! And it will find the CMake with other system libraries.
If you want to reuse the same build files for other platforms, that's only when this project shines as you rebuild Boost properly for other platforms (like Android or iOS).

**Comment by Orphis** [comment]
The name of the artifacts should now match the official Boost release.
But really, don't try to use the standalone build, it's a bad idea for many reasons!

**Comment by Zer0xFF** [comment]
> And why would you build the libraries twice? Do you partially build some libraries from CMake and some others from QMake?

Play can be broken down into 3 libraries, (CodeGen, Framework, Play) the boost libraries are used as part of Play's libraries (mainly Framework) and it's also used in the qt ui, Play's libraries are built with cmake, while the ui is built with qmake, so I'm trying to use the same boost library for both of them.

> Well QtCreator can use CMake files directly too. So you don't need QMake for that.
I'll have a look at cmake in qt creator.

Thanks

**Comment by Orphis** [comment]
> Play can be broken down into 3 libraries, (CodeGen, Framework, Play) the boost libraries are used as part of Play's libraries (mainly Framework) and it's also used in the qt ui, Play's libraries are built with cmake, while the ui is built with qmake, so I'm trying to use the same boost library for both of them.

That's not a problem you will have if you use a proper coherent CMake build for all of it.

**Comment by Zer0xFF** [comment]
> That's not a problem you will have if you use a proper coherent CMake build for all of it.

that what've been trying to do and thanks to your qt creator hint, I found out that qt creator can read cmakelists.txt and would open it as psudo-project, given that I've the entire project building from a single cmakefile, just ubuntu as of now.

**Comment by Orphis** [comment]
Ubuntu is a good start!

**Pull request closed without merging**
