### PR TITLE
Enable boost::unique_lock for boost::locale

### LINKED ISSUE #39: Build failed with boost::locale
Hi,
I just added the boost::locale to my project as dependency and the build failed. It seems that boost::unique_lock is not found during the build. The other selected libraries (log, program_options) works fine. Boost::thread is compiled as well.

-- The CXX compiler identification is GNU 6.3.0
-- (K)ubuntu 17.04
-- CMake 3.8.2
-- failed with pre-set url and with sourcefource archive
-- tried with ICU, ICONV, STD and POSIX-Backend

```/home/tim/Projects/StellarPioneers/cmake-build-debug/lib/3rd_party/boost-cmake/boost/boost_1_63_0/libs/locale/src/shared/generator.cpp: In member function ‘std::locale boost::locale::generator::generate(const std::locale&, const string&) const’:
/home/tim/Projects/StellarPioneers/cmake-build-debug/lib/3rd_party/boost-cmake/boost/boost_1_63_0/libs/locale/src/shared/generator.cpp:122:17: error: ‘unique_lock’ is not a member of ‘boost’
                 boost::unique_lock<boost::mutex> guard(d->cached_lock);
                 ^~~~~
/home/tim/Projects/StellarPioneers/cmake-build-debug/lib/3rd_party/boost-cmake/boost/boost_1_63_0/libs/locale/src/shared/generator.cpp:122:48: error: expected primary-expression before ‘>’ token
                 boost::unique_lock<boost::mutex> guard(d->cached_lock);
                                                ^
/home/tim/Projects/StellarPioneers/cmake-build-debug/lib/3rd_party/boost-cmake/boost/boost_1_63_0/libs/locale/src/shared/generator.cpp:122:70: error: ‘guard’ was not declared in this scope
                 boost::unique_lock<boost::mutex> guard(d->cached_lock);
                                                                      ^
/home/tim/Projects/StellarPioneers/cmake-build-debug/lib/3rd_party/boost-cmake/boost/boost_1_63_0/libs/locale/src/shared/generator.cpp:150:17: error: ‘unique_lock’ is not a member of ‘boost’
                 boost::unique_lock<boost::mutex> guard(d->cached_lock);
                 ^~~~~
/home/tim/Projects/StellarPioneers/cmake-build-debug/lib/3rd_party/boost-cmake/boost/boost_1_63_0/libs/locale/src/shared/generator.cpp:150:48: error: expected primary-expression before ‘>’ token
                 boost::unique_lock<boost::mutex> guard(d->cached_lock);
                                                ^
/home/tim/Projects/StellarPioneers/cmake-build-debug/lib/3rd_party/boost-cmake/boost/boost_1_63_0/libs/locale/src/shared/generator.cpp:150:70: error: ‘guard’ was not declared in this scope
                 boost::unique_lock<boost::mutex> guard(d->cached_lock);
                                                                      ^
/home/tim/Projects/StellarPioneers/cmake-build-debug/lib/3rd_party/boost-cmake/boost/boost_1_63_0/libs/locale/src/shared/date_time.cpp: In function ‘std::__cxx11::string boost::locale::time_zone::global()’:
/home/tim/Projects/StellarPioneers/cmake-build-debug/lib/3rd_party/boost-cmake/boost/boost_1_63_0/libs/locale/src/shared/date_time.cpp:447:9: error: ‘unique_lock’ is not a member of ‘boost’
         boost::unique_lock<boost::mutex> lock(tz_mutex());
         ^~~~~
/home/tim/Projects/StellarPioneers/cmake-build-debug/lib/3rd_party/boost-cmake/boost/boost_1_63_0/libs/locale/src/shared/date_time.cpp:447:40: error: expected primary-expression before ‘>’ token
         boost::unique_lock<boost::mutex> lock(tz_mutex());
                                        ^
/home/tim/Projects/StellarPioneers/cmake-build-debug/lib/3rd_party/boost-cmake/boost/boost_1_63_0/libs/locale/src/shared/date_time.cpp:447:57: error: ‘lock’ was not declared in this scope
         boost::unique_lock<boost::mutex> lock(tz_mutex());
                                                         ^
/home/tim/Projects/StellarPioneers/cmake-build-debug/lib/3rd_party/boost-cmake/boost/boost_1_63_0/libs/locale/src/shared/date_time.cpp: In function ‘std::__cxx11::string boost::locale::time_zone::global(const string&)’:
/home/tim/Projects/StellarPioneers/cmake-build-debug/lib/3rd_party/boost-cmake/boost/boost_1_63_0/libs/locale/src/shared/date_time.cpp:453:9: error: ‘unique_lock’ is not a member of ‘boost’
         boost::unique_lock<boost::mutex> lock(tz_mutex());
         ^~~~~
/home/tim/Projects/StellarPioneers/cmake-build-debug/lib/3rd_party/boost-cmake/boost/boost_1_63_0/libs/locale/src/shared/date_time.cpp:453:40: error: expected primary-expression before ‘>’ token
         boost::unique_lock<boost::mutex> lock(tz_mutex());
                                        ^
/home/tim/Projects/StellarPioneers/cmake-build-debug/lib/3rd_party/boost-cmake/boost/boost_1_63_0/libs/locale/src/shared/date_time.cpp:453:57: error: ‘lock’ was not declared in this scope
         boost::unique_lock<boost::mutex> lock(tz_mutex());
                                                         ^
/home/tim/Projects/StellarPioneers/cmake-build-debug/lib/3rd_party/boost-cmake/boost/boost_1_63_0/libs/locale/src/shared/localization_backend.cpp: In static member function ‘static boost::locale::localization_backend_manager boost::locale::localization_backend_manager::global()’:
/home/tim/Projects/StellarPioneers/cmake-build-debug/lib/3rd_party/boost-cmake/boost/boost_1_63_0/libs/locale/src/shared/localization_backend.cpp:248:13: error: ‘unique_lock’ is not a member of ‘boost’
             boost::unique_lock<boost::mutex> lock(localization_backend_manager_mutex());
             ^~~~~
/home/tim/Projects/StellarPioneers/cmake-build-debug/lib/3rd_party/boost-cmake/boost/boost_1_63_0/libs/locale/src/shared/localization_backend.cpp:248:44: error: expected primary-expression before ‘>’ token
             boost::unique_lock<boost::mutex> lock(localization_backend_manager_mutex());
                                            ^
/home/tim/Projects/StellarPioneers/cmake-build-debug/lib/3rd_party/boost-cmake/boost/boost_1_63_0/libs/locale/src/shared/localization_backend.cpp:248:87: error: ‘lock’ was not declared in this scope
             boost::unique_lock<boost::mutex> lock(localization_backend_manager_mutex());
                                                                                       ^
/home/tim/Projects/StellarPioneers/cmake-build-debug/lib/3rd_party/boost-cmake/boost/boost_1_63_0/libs/locale/src/shared/localization_backend.cpp: In static member function ‘static boost::locale::localization_backend_manager boost::locale::localization_backend_manager::global(const boost::locale::localization_backend_manager&)’:
/home/tim/Projects/StellarPioneers/cmake-build-debug/lib/3rd_party/boost-cmake/boost/boost_1_63_0/libs/locale/src/shared/localization_backend.cpp:254:13: error: ‘unique_lock’ is not a member of ‘boost’
             boost::unique_lock<boost::mutex> lock(localization_backend_manager_mutex());
             ^~~~~
/home/tim/Projects/StellarPioneers/cmake-build-debug/lib/3rd_party/boost-cmake/boost/boost_1_63_0/libs/locale/src/shared/localization_backend.cpp:254:44: error: expected primary-expression before ‘>’ token
             boost::unique_lock<boost::mutex> lock(localization_backend_manager_mutex());
                                            ^
/home/tim/Projects/StellarPioneers/cmake-build-debug/lib/3rd_party/boost-cmake/boost/boost_1_63_0/libs/locale/src/shared/localization_backend.cpp:254:87: error: ‘lock’ was not declared in this scope
             boost::unique_lock<boost::mutex> lock(localization_backend_manager_mutex());
```

### PR DESCRIPTION
**Pull request by ghost**
boost::locale uses the deprecated feature boost::unique_lock. For compiling boost::locale, BOOST_THREAD_PROVIDES_NESTED_LOCKS has to be set. See http://www.boost.org/doc/libs/1_64_0/doc/html/thread/build.html#thread.build.configuration.nested_lock.
fixes #39

### CODE REVIEW

**Comment by Orphis** [comment]
This shouldn't be necessary.

**Comment by rcdailey** [comment]
@Orphis Why is this not necessary? I'm hitting this on `master` right now with boost 1.69

**Comment by Orphis** [comment]
What error are you getting actually?

**Comment by rcdailey** [comment]
I'm getting errors shown in this issue: https://github.com/Orphis/boost-cmake/issues/39

Haven't checked if they are 100% identical, but they're very similar. And involving the same library.

But even if I get past that issue, certain parts of your boost library do not compile in CLR libraries. There's also no option to build shared libraries since your CMake scripts hard-code the `add_library()` as `STATIC`.

**Comment by Orphis** [comment]
I'm guessing that some new files don't have the required includes and require transitive ones to get the   `boost::unique_lock` headers. I did fix that upstream a while ago. The full error is required to make progress.

As for CLR, it would help if the errors where reported here (in case the build is different) or to Boost libraries (I know some won't build for CLR).

And no, I don't support SHARED builds, there's no testing for it and I'm not going to claim it's working by just removing the STATIC keyword. Some libraries are more tricky in that regard as they use thread local storage.

**Comment by rcdailey** [comment]
@Orphis I apologize for the lack of detail, I was not at my work machine so I couldn't provide more information. Let me open a separate issue so we can keep this PR closed to discussion.

**Pull request closed without merging**
