### PR TITLE
Bump CMake requirement to 3.12

### PR DESCRIPTION
**Pull request by Orphis**

### CODE REVIEW

**Review by rcdailey — COMMENTED** [review]
Have you looked at a way to manage one version of CMake that you feed into both spots for maintainability?

**Comment by Orphis** [comment]
Do you mean extracting the version number into a variable?
Well, yes, but I'm changing to Azure Pipelines right now, so I'm basically rewriting those scripts. First I got it to build, now I'll clean it up and merge Windows support in the travis.sh properly.

**Comment by janisozaur** [comment]
What's the functionality of 3.12 that makes this a requirement?

**Comment by Orphis** [comment]
`FetchContent` is. It's superior to the old hack and provides a good way to override the location you fetch the sources from.

Feel free to fork locally and provide your own mechanism to download the Boost sources if you prefer!

**Comment by janisozaur** [comment]
https://cmake.org/cmake/help/v3.11/module/FetchContent.html documents this as available in 3.11 already. Doesn't meet my end goal of 3.10 support, but still overly high.

**Pull request merged**
