### PR TITLE
Change some set_target_properties to target_compile_definitions()

### PR DESCRIPTION
**Pull request by Orphis**

### CODE REVIEW

**Comment by rcdailey** [comment]
Any reason you do PRs for your own commits? It's a bit unusual. Most folks just push directly to the remote branch.

**Comment by Orphis** [comment]
Because I develop on only one platform at a time, I want to make sure I don't break anything by running CI on every change. I'm just human, I make mistakes too!

If I push to master directly, that's because I've done a very minor change to some already tested changes in CI or just documentation.

**Comment by rcdailey** [comment]
Ah, that's a good point. I guess Travis doesn't build branches without pull requests attached? And that's not configurable? At my day job, I have my CI/CD system set up to build all branches, so I get feedback without a pull request. Never used Travis before so I'm not sure how flexible it is.

**Comment by Orphis** [comment]
It's harder to get feedback on some pull requests then though. With a PR, it gives opportunity for others to give feedback too.

I can get Azure-Pipelines to check other branches too if I want, but since I create a PR anyway, it would just make double the work.

**Pull request merged**
